package com.example.EmployeeDB.employee;
import java.time.*;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

//Creates Employee as an entity in the database
@Entity
public class Employee 
{
    @Id //Makes ID the primary key
    @GeneratedValue(strategy = GenerationType.AUTO) //Autp Generates the ID
    private long id;                //Employee's Id
    
    private String firstName;       //Employee's First name 
    private String lastName;        //Employee's Last name 
    private String email;           //Employee's email
    private long phone;             //Employee's phone number
    private LocalDate dob;          //Employee's date of birth
    private String jobtitle;        //Employee's job title
    private String department;      //Employee's Department of the job
    private String city;            //City the employee works in
    private LocalDate startDate;    //Date employee started the job
    private LocalDate endDate;    //Date employee ended the job
    private String reportingManager;//Name of reporting manager

    //Empty constructor for employee class
    public Employee()
    {

    }

    //Constructor for employee class with all arguments except employee id as that will be autogenerated
    public Employee(String firstName, String lastName, String email, long phone, LocalDate dob, String jobtitle, String department, String city, LocalDate startDate, LocalDate endDate, String reportingManager)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.dob = dob;
        this.jobtitle = jobtitle;
        this.department = department;
        this.city = city;
        this.startDate = startDate;
        this.endDate = endDate;
        this.reportingManager = reportingManager;
    }

    
    public long getId() 
    {
        return id;
    }

    public void setId(long id) 
    {
        this.id = id;
    }

    public String getFirstName() 
    {
        return firstName;
    }

    public void setFirstName(String firstName) 
    {
        this.firstName = firstName;
    }

    public String getLastName() 
    {
        return lastName;
    }

    public void setLastName(String lastName) 
    {
        this.lastName = lastName;
    }

    public String getEmail() 
    {
        return email;
    }

    public void setEmail(String email) 
    {
        this.email = email;
    }

    public long getPhone() 
    {
        return phone;
    }

    public void setPhone(long phone) 
    {
        this.phone = phone;
    }

    public LocalDate getDob() 
    {
        return dob;
    }

    public void setDob(LocalDate dob) 
    {
        this.dob = dob;
    }

    public String getJobtitle() 
    {
        return jobtitle;
    }

    public void setJobtitle(String jobtitle) 
    {
        this.jobtitle = jobtitle;
    }

    public String getDepartment() 
    {
        return department;
    }

    public void setDepartment(String department) 
    {
        this.department = department;
    }

    public String getCity() 
    {
        return city;
    }

    public void setCity(String city) 
    {
        this.city = city;
    }

    public LocalDate getStartDate() 
    {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) 
    {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public String getReportingManager() 
    {
        return reportingManager;
    }

    public void setReportingManager(String reportingManager) 
    {
        this.reportingManager = reportingManager;
    }
}